apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-agent
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      name: grafana-agent
  template:
    metadata:
      labels:
        name: grafana-agent
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - args:
        - -config.file=/etc/grafana-agent/agent.yaml
        command:
        - /bin/agent
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: grafana-agent:v0.23.0
        imagePullPolicy: IfNotPresent
        name: agent
        volumeMounts:
        - mountPath: /etc/grafana-agent
          name: grafana-agent
      serviceAccount: grafana-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: grafana-agent
        name: grafana-agent
